const express=require('express'),router=express.Router(),pool=require('../config/db');

router.post('/:slug/chatbot',async(req,res)=>{try{const s=(await pool.query('SELECT * FROM stores WHERE slug=$1',[req.params.slug])).rows[0];if(!s)return res.status(404).json({error:'Not found'});const{message}=req.body;const m=(message||'').toLowerCase();const c=s.currency||'DZD';let r=`Welcome to ${s.store_name}! How can I help you?`;if(m.includes('shipping')||m.includes('delivery')||m.includes('livraison')||m.includes('توصيل'))r=`Shipping available to all 58 wilayas! Standard: 400 ${c}.`;else if(m.includes('payment')||m.includes('pay')||m.includes('paiement')||m.includes('دفع'))r=`We accept Cash on Delivery, CCP, BaridiMob, and Bank Transfer.`;else if(m.includes('product')||m.includes('best')||m.includes('منتج'))r=`Check our catalog for the latest products!`;else if(m.includes('hello')||m.includes('hi')||m.includes('bonjour')||m.includes('سلام'))r=`Welcome to ${s.store_name}! How can I assist you?`;else if(m.includes('contact')||m.includes('اتصال'))r=`Contact us at ${s.contact_phone||'our store'}.`;res.json({response:r,suggestedActions:[{label:'Shipping rates',action:'shipping_rates'},{label:'Best sellers',action:'best_sellers'},{label:'Contact info',action:'contact'}]});}catch(e){res.status(500).json({error:'Chatbot error'});}});

router.post('/detect-fake',async(req,res)=>{try{const{store_id,customer_phone}=req.body;let score=0,flags=[];try{const c=parseInt((await pool.query("SELECT COUNT(*) FROM orders WHERE store_id=$1 AND customer_phone=$2 AND status='cancelled'",[store_id,customer_phone])).rows[0].count);if(c>=3){score+=40;flags.push('High cancellations');}else if(c>=1){score+=15;flags.push('Previous cancellations');}}catch(e){}res.json({fakeScore:Math.min(score,100),riskLevel:score>=60?'high':score>=30?'medium':'low',flags});}catch(e){res.status(500).json({error:'Detection failed'});}});

router.post('/cart-recovery/suggest',async(req,res)=>{res.json({messages:[{sequence:1,delay:'30m',message:'You left items in your cart!'},{sequence:2,delay:'6h',message:'Items still waiting!'},{sequence:3,delay:'24h',message:'Last chance! Use COMEBACK10 for 10% off!'}]});});

module.exports=router;
