const express=require('express'),router=express.Router(),pool=require('../config/db'),{authMiddleware}=require('../middleware/auth'),slugify=require('slugify');

// Products
router.get('/stores/:sid/products',authMiddleware(['store_owner','store_staff']),async(req,res)=>{try{const{search,category}=req.query;let q='SELECT p.*,c.name as category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.store_id=$1';const params=[req.params.sid];if(search){params.push(`%${search}%`);q+=` AND p.name ILIKE $${params.length}`;}if(category){params.push(category);q+=` AND p.category_id=$${params.length}`;}q+=' ORDER BY p.created_at DESC';const r=await pool.query(q,params);const count=await pool.query('SELECT COUNT(*) FROM products WHERE store_id=$1',[req.params.sid]);const products=r.rows.map(p=>{let imgs=p.images;if(typeof imgs==='string')try{imgs=JSON.parse(imgs);}catch(e){imgs=[];}if(!Array.isArray(imgs))imgs=[];return{...p,name_en:p.name,name_fr:p.name,name_ar:p.name,images:imgs,thumbnail:imgs[0]||null,compare_at_price:p.compare_price};});res.json({products,total:parseInt(count.rows[0].count)});}catch(e){res.status(500).json({error:e.message});}});

router.post('/stores/:sid/products',authMiddleware(['store_owner','store_staff']),async(req,res)=>{try{const{name_en,description_en,price,compare_at_price,cost_price,sku,barcode,stock_quantity,category_id,images,is_featured,tags,variants}=req.body;const name=name_en||'Product';const slug=slugify(name,{lower:true,strict:true})+'-'+Date.now().toString(36);let imgs=Array.isArray(images)?images:[];const r=await pool.query('INSERT INTO products(store_id,category_id,name,slug,description,price,compare_price,cost_price,sku,barcode,stock_quantity,images,is_featured,tags,variants) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15::jsonb) RETURNING *',[req.params.sid,category_id||null,name,slug,description_en||null,price,compare_at_price||null,cost_price||null,sku||null,barcode||null,stock_quantity||0,JSON.stringify(imgs),is_featured||false,tags||[],variants?JSON.stringify(variants):null]);const p=r.rows[0];res.status(201).json({...p,name_en:p.name,thumbnail:imgs[0]||null,compare_at_price:p.compare_price});}catch(e){console.error(e);res.status(500).json({error:e.message});}});

router.put('/stores/:sid/products/:pid',authMiddleware(['store_owner','store_staff']),async(req,res)=>{try{const f=req.body;const u=[],v=[];let i=1;const sm={name_en:'name',description_en:'description',price:'price',compare_at_price:'compare_price',cost_price:'cost_price',sku:'sku',barcode:'barcode',stock_quantity:'stock_quantity',category_id:'category_id',is_active:'is_active',is_featured:'is_featured',track_inventory:'track_inventory'};for(const[k,col]of Object.entries(sm)){if(f[k]!==undefined){u.push(`${col}=$${i}`);v.push(f[k]);i++;}}if(f.images!==undefined){u.push(`images=$${i}::jsonb`);v.push(JSON.stringify(Array.isArray(f.images)?f.images:[]));i++;}if(f.tags!==undefined){u.push(`tags=$${i}`);v.push(f.tags||[]);i++;}if(f.variants!==undefined){u.push(`variants=$${i}::jsonb`);v.push(f.variants?JSON.stringify(f.variants):null);i++;}if(!u.length)return res.status(400).json({error:'Nothing'});v.push(req.params.pid,req.params.sid);const r=await pool.query(`UPDATE products SET ${u.join(',')},updated_at=NOW() WHERE id=$${i} AND store_id=$${i+1} RETURNING *`,v);if(!r.rows.length)return res.status(404).json({error:'Not found'});const p=r.rows[0];let imgs=p.images;if(typeof imgs==='string')try{imgs=JSON.parse(imgs);}catch(e){imgs=[];}if(!Array.isArray(imgs))imgs=[];res.json({...p,name_en:p.name,images:imgs,thumbnail:imgs[0]||null,compare_at_price:p.compare_price});}catch(e){res.status(500).json({error:e.message});}});

router.delete('/stores/:sid/products/:pid',authMiddleware(['store_owner']),async(req,res)=>{try{await pool.query('DELETE FROM products WHERE id=$1 AND store_id=$2',[req.params.pid,req.params.sid]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

// Categories
router.get('/stores/:sid/categories',authMiddleware(['store_owner','store_staff']),async(req,res)=>{try{const r=await pool.query('SELECT c.*,(SELECT COUNT(*) FROM products WHERE category_id=c.id) as product_count FROM categories c WHERE c.store_id=$1 ORDER BY c.sort_order',[req.params.sid]);res.json(r.rows.map(c=>({...c,name_en:c.name,name_fr:c.name,name_ar:c.name,image:c.image_url})));}catch(e){res.json([]);}});
router.post('/stores/:sid/categories',authMiddleware(['store_owner']),async(req,res)=>{try{const{name_en,image,parent_id}=req.body;const name=name_en||'Category';const slug=slugify(name,{lower:true,strict:true})+'-'+Date.now().toString(36);const r=await pool.query('INSERT INTO categories(store_id,name,slug,image_url,parent_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.params.sid,name,slug,image||null,parent_id||null]);res.status(201).json({...r.rows[0],name_en:r.rows[0].name});}catch(e){res.status(500).json({error:e.message});}});

// Coupons stub
router.get('/stores/:sid/coupons',authMiddleware(['store_owner']),async(req,res)=>res.json([]));
router.post('/stores/:sid/coupons',authMiddleware(['store_owner']),async(req,res)=>res.json({message:'Coming soon'}));

// Apps
router.get('/stores/:sid/apps',authMiddleware(['store_owner']),async(req,res)=>{try{res.json((await pool.query('SELECT * FROM store_apps WHERE store_id=$1',[req.params.sid])).rows);}catch(e){res.json([]);}});
router.post('/stores/:sid/apps/install',authMiddleware(['store_owner']),async(req,res)=>{try{const{app_name,app_slug}=req.body;const ex=await pool.query('SELECT id,is_active FROM store_apps WHERE store_id=$1 AND app_slug=$2',[req.params.sid,app_slug]);if(ex.rows.length){const r=await pool.query('UPDATE store_apps SET is_active=NOT is_active WHERE id=$1 RETURNING *',[ex.rows[0].id]);return res.json(r.rows[0]);}const r=await pool.query('INSERT INTO store_apps(store_id,app_name,app_slug,is_active) VALUES($1,$2,$3,TRUE) RETURNING *',[req.params.sid,app_name,app_slug]);res.status(201).json(r.rows[0]);}catch(e){res.status(500).json({error:e.message});}});

module.exports=router;
