const express=require('express'),router=express.Router(),bcrypt=require('bcryptjs'),pool=require('../config/db'),{authMiddleware,generateToken}=require('../middleware/auth'),slugify=require('slugify');

// Register — DB: full_name, email(NOT NULL), phone(NOT NULL), password_hash
router.post('/register',async(req,res)=>{try{const{name,email,phone,password,address,city,wilaya}=req.body;if(!name||!email||!phone||!password)return res.status(400).json({error:'All fields required'});const dup=await pool.query('SELECT id FROM store_owners WHERE email=$1 OR phone=$2',[email,phone]);if(dup.rows.length)return res.status(409).json({error:'Email or phone already registered'});const hash=await bcrypt.hash(password,12);const r=await pool.query('INSERT INTO store_owners(full_name,email,phone,password_hash,address,city,wilaya) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[name,email,phone,hash,address||null,city||null,wilaya||null]);const o=r.rows[0];const token=generateToken({id:o.id,role:'store_owner',name:o.full_name});res.status(201).json({token,owner:{id:o.id,name:o.full_name,email:o.email,phone:o.phone,subscription_plan:o.subscription_plan,subscription_end:o.subscription_end}});}catch(e){console.error(e);res.status(500).json({error:'Registration failed',detail:e.message});}});

// Login (email OR phone)
router.post('/login',async(req,res)=>{try{const{identifier,password}=req.body;if(!identifier||!password)return res.status(400).json({error:'Credentials required'});let r=await pool.query('SELECT * FROM store_owners WHERE email=$1',[identifier]);if(!r.rows.length)r=await pool.query('SELECT * FROM store_owners WHERE phone=$1',[identifier]);if(!r.rows.length)return res.status(401).json({error:'Invalid credentials'});const o=r.rows[0];if(o.is_active===false)return res.status(403).json({error:'Account suspended'});if(!(await bcrypt.compare(password,o.password_hash)))return res.status(401).json({error:'Invalid credentials'});const token=generateToken({id:o.id,role:'store_owner',name:o.full_name});const stores=await pool.query('SELECT * FROM stores WHERE owner_id=$1',[o.id]);res.json({token,owner:{id:o.id,name:o.full_name,email:o.email,phone:o.phone,subscription_plan:o.subscription_plan,subscription_end:o.subscription_end},stores:stores.rows.map(s=>({...s,name:s.store_name,is_live:s.is_published,logo:s.logo_url}))});}catch(e){res.status(500).json({error:'Login failed',detail:e.message});}});

// Create store — DB: store_name, slug, owner_id
router.post('/stores',authMiddleware(['store_owner']),async(req,res)=>{try{const{name,description}=req.body;const slug=slugify(name,{lower:true,strict:true})+'-'+Date.now().toString(36);const r=await pool.query('INSERT INTO stores(owner_id,store_name,slug,description,is_published,is_active) VALUES($1,$2,$3,$4,TRUE,TRUE) RETURNING *',[req.user.id,name,slug,description||null]);try{await pool.query('INSERT INTO payment_settings(store_id,cod_enabled) VALUES($1,TRUE)',[r.rows[0].id]);}catch(e){}const s=r.rows[0];res.status(201).json({...s,name:s.store_name,is_live:s.is_published,logo:s.logo_url});}catch(e){res.status(500).json({error:'Failed',detail:e.message});}});

// Get stores
router.get('/stores',authMiddleware(['store_owner']),async(req,res)=>{try{const r=await pool.query(`SELECT s.*,(SELECT COUNT(*) FROM products WHERE store_id=s.id) as product_count,(SELECT COUNT(*) FROM orders WHERE store_id=s.id) as order_count,(SELECT COALESCE(SUM(total),0) FROM orders WHERE store_id=s.id AND payment_status='paid') as revenue FROM stores s WHERE s.owner_id=$1 ORDER BY s.created_at DESC`,[req.user.id]);res.json(r.rows.map(s=>({...s,name:s.store_name,is_live:s.is_published,logo:s.logo_url})));}catch(e){res.status(500).json({error:e.message});}});

// Dashboard
router.get('/stores/:sid/dashboard',authMiddleware(['store_owner']),async(req,res)=>{try{const sid=req.params.sid;const store=await pool.query('SELECT * FROM stores WHERE id=$1 AND owner_id=$2',[sid,req.user.id]);if(!store.rows.length)return res.status(404).json({error:'Not found'});const s=store.rows[0];let to=0,tr=0,tp=0,tc=0,ro=[],sd=[];try{to=parseInt((await pool.query('SELECT COUNT(*) FROM orders WHERE store_id=$1',[sid])).rows[0].count);}catch(e){}try{tr=parseFloat((await pool.query("SELECT COALESCE(SUM(total),0) as t FROM orders WHERE store_id=$1 AND payment_status='paid'",[sid])).rows[0].t);}catch(e){}try{tp=parseInt((await pool.query('SELECT COUNT(*) FROM products WHERE store_id=$1',[sid])).rows[0].count);}catch(e){}try{tc=parseInt((await pool.query('SELECT COUNT(*) FROM customers WHERE store_id=$1',[sid])).rows[0].count);}catch(e){}try{ro=(await pool.query('SELECT * FROM orders WHERE store_id=$1 ORDER BY created_at DESC LIMIT 10',[sid])).rows;}catch(e){}try{sd=(await pool.query("SELECT DATE(created_at) as date,COUNT(*) as orders,COALESCE(SUM(total),0) as revenue FROM orders WHERE store_id=$1 AND created_at>NOW()-INTERVAL '30 days' GROUP BY DATE(created_at) ORDER BY date",[sid])).rows;}catch(e){}res.json({store:{...s,name:s.store_name,is_live:s.is_published,logo:s.logo_url,store_visits:s.total_visits},stats:{totalOrders:to,totalRevenue:tr,totalProducts:tp,totalCustomers:tc,storeVisits:s.total_visits||0,avgOrderValue:to>0?(tr/to).toFixed(2):0},recentOrders:ro.map(o=>({...o,order_number:'ORD-'+String(o.order_number).padStart(5,'0'),discount_amount:o.discount})),salesData:sd});}catch(e){res.status(500).json({error:e.message});}});

// Update store
router.put('/stores/:sid',authMiddleware(['store_owner']),async(req,res)=>{try{const sid=req.params.sid;const own=await pool.query('SELECT id FROM stores WHERE id=$1 AND owner_id=$2',[sid,req.user.id]);if(!own.rows.length)return res.status(404).json({error:'Not found'});const f=req.body;const map={name:'store_name',store_name:'store_name',description:'description',logo:'logo_url',logo_url:'logo_url',favicon:'favicon_url',primary_color:'primary_color',secondary_color:'secondary_color',accent_color:'accent_color',bg_color:'bg_color',currency:'currency',is_live:'is_published',is_published:'is_published',meta_title:'meta_title',meta_description:'meta_description',hero_title:'hero_title',hero_subtitle:'hero_subtitle',contact_email:'contact_email',contact_phone:'contact_phone',contact_address:'contact_address',social_facebook:'social_facebook',social_instagram:'social_instagram',social_tiktok:'social_tiktok'};const u=[],v=[];let i=1;for(const[k,val]of Object.entries(f)){const col=map[k];if(!col)continue;u.push(`${col}=$${i}`);v.push(val);i++;}if(u.length){v.push(sid);await pool.query(`UPDATE stores SET ${u.join(',')},updated_at=NOW() WHERE id=$${i}`,v);}
// Payment settings
const pm={enable_cod:'cod_enabled',enable_ccp:'ccp_enabled',ccp_account:'ccp_account',ccp_name:'ccp_name',enable_baridimob:'baridimob_enabled',baridimob_rip:'baridimob_rip',enable_bank_transfer:'bank_transfer_enabled',bank_name:'bank_name',bank_account:'bank_account',bank_rib:'bank_rib'};const pu=[],pv=[];let pi=1;for(const[k,val]of Object.entries(f)){const col=pm[k];if(!col)continue;pu.push(`${col}=$${pi}`);pv.push(val);pi++;}if(pu.length){pv.push(sid);try{await pool.query(`UPDATE payment_settings SET ${pu.join(',')},updated_at=NOW() WHERE store_id=$${pi}`,pv);}catch(e){}}
const r=await pool.query('SELECT * FROM stores WHERE id=$1',[sid]);const pay=await pool.query('SELECT * FROM payment_settings WHERE store_id=$1',[sid]).catch(()=>({rows:[{}]}));const s=r.rows[0];const p=pay.rows[0]||{};res.json({...s,name:s.store_name,is_live:s.is_published,logo:s.logo_url,enable_cod:p.cod_enabled,enable_ccp:p.ccp_enabled,ccp_account:p.ccp_account,ccp_name:p.ccp_name,enable_baridimob:p.baridimob_enabled,baridimob_rip:p.baridimob_rip,enable_bank_transfer:p.bank_transfer_enabled,bank_name:p.bank_name,bank_account:p.bank_account,bank_rib:p.bank_rib});}catch(e){res.status(500).json({error:e.message});}});

// Staff
router.get('/stores/:sid/staff',authMiddleware(['store_owner']),async(req,res)=>{try{res.json((await pool.query('SELECT id,name,email,phone,role,is_active,created_at FROM store_staff WHERE store_id=$1',[req.params.sid])).rows);}catch(e){res.json([]);}});
router.post('/stores/:sid/staff',authMiddleware(['store_owner']),async(req,res)=>{try{const{name,email,phone,password,role}=req.body;const hash=await bcrypt.hash(password,12);const r=await pool.query('INSERT INTO store_staff(store_id,name,email,phone,password_hash,role) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,email,phone,role,created_at',[req.params.sid,name,email,phone,hash,role]);res.status(201).json(r.rows[0]);}catch(e){res.status(500).json({error:e.message});}});
router.post('/staff/login',async(req,res)=>{try{const{storeSlug,email,password}=req.body;const store=await pool.query('SELECT id FROM stores WHERE slug=$1',[storeSlug]);if(!store.rows.length)return res.status(404).json({error:'Store not found'});const staff=await pool.query('SELECT * FROM store_staff WHERE store_id=$1 AND email=$2 AND is_active=TRUE',[store.rows[0].id,email]);if(!staff.rows.length)return res.status(401).json({error:'Invalid'});if(!(await bcrypt.compare(password,staff.rows[0].password_hash)))return res.status(401).json({error:'Invalid'});const t=generateToken({id:staff.rows[0].id,role:'store_staff',staffRole:staff.rows[0].role,storeId:store.rows[0].id,name:staff.rows[0].name});res.json({token:t,staff:{id:staff.rows[0].id,name:staff.rows[0].name,role:staff.rows[0].role}});}catch(e){res.status(500).json({error:e.message});}});

// Domains (stub)
router.get('/stores/:sid/domains',authMiddleware(['store_owner']),async(req,res)=>res.json([]));
router.post('/stores/:sid/domains',authMiddleware(['store_owner']),async(req,res)=>res.json({message:'Coming soon'}));

// Profile
router.get('/profile',authMiddleware(['store_owner']),async(req,res)=>{try{const r=await pool.query('SELECT * FROM store_owners WHERE id=$1',[req.user.id]);if(!r.rows.length)return res.status(404).json({error:'Not found'});res.json({...r.rows[0],name:r.rows[0].full_name});}catch(e){res.status(500).json({error:e.message});}});

module.exports=router;
